module Autoport
  # Outputs a skeleton default.nix with some values filled-in
  class DeviceFile
    TODO = "TODO!"

    def initialize(
      bootimg:,
      device_name:,
      full_codename:,
      soc:,
      manufacturer:,
      model:,
      system_root_image:,
      ab_update:,
      has_vendor_partition:
    )
      @bootimg = bootimg
      @device_name = device_name
      @full_codename = full_codename
      @soc = soc
      @manufacturer = manufacturer
      @model = model
      @has_vendor_partition = has_vendor_partition
      @system_root_image = system_root_image
      @ab_update = ab_update
    end

    def hex(num)
      "0x" + Integer(num).to_s(16).rjust(8, "0")
    end

    def number(num)
      Integer(num).to_s()
    end

    def kernel_cmdline()
      @bootimg.cmdline.split(" ")
    end

    def usb_mode()
      if @bootimg.kernel.config("CONFIG_USB_CONFIGFS") == "y"
        "gadgetfs"
      elsif @bootimg.kernel.config("CONFIG_USB_G_ANDROID") == "y"
        "android_usb"
      else
      end
    end

    def rndis_gadget()
      @rndis_gadget ||=
        if @bootimg.kernel.config("CONFIG_USB_F_RMNET_BAM") == "y"
          "rndis_bam.rndis"
        elsif @bootimg.kernel.config("CONFIG_USB_F_GSI") == "y"
          "gsi.rndis"
        else
          nil
        end

      @rndis_gadget
    end

    def get_contents()
<<EOF
{ pkgs, ... }:

/*
 * This file has been generated by autoport.
 * **Do not** open a Pull Request without having verified the port works.
 */
{
  mobile.device.name = "#{@full_codename}";
  mobile.device.identity = {
    name = "#{@model}";
    manufacturer = "#{@manufacturer}";
  };

  mobile.hardware = {
    soc = "#{@soc}";
    ram = 1024 * 0/* (in MB) To be filled by the user */;
    screen = {
      width = 0/* To be filled by the user */; height = 0/* To be filled by the user */;
    };
  };

  mobile.boot.stage-1 = {
    kernel.package = pkgs.callPackage ./kernel { };
  };

  mobile.system.android.device_name = "#{@device_name}";
  mobile.system.android = {
#{
if @ab_update
  # This applies to any device with A/B (e.g. walleye)
<<EOS
    # This device has an A/B partition scheme.
    ab_partitions = true;
EOS
elsif @system_root_image
  # This applies to `xiaomi-lavender`
<<EOS
    # This device adds skip_initramfs to cmdline for normal boots
    boot_as_recovery = true;

    # Though this device has "boot_as_recovery", it still has a classic
    # recovery partition for recovery.
    has_recovery_partition = true;
EOS
else "" end
}
    bootimg.flash = {
      offset_base = "#{hex(@bootimg.base)}";
      offset_kernel = "#{hex(@bootimg.kernel_offset)}";
      offset_ramdisk = "#{hex(@bootimg.ramdisk_offset)}";
      offset_second = "#{hex(@bootimg.second_offset)}";
      offset_tags = "#{hex(@bootimg.tags_offset)}";
      pagesize = "#{number(@bootimg.pagesize)}";
    };
  };

#{
  if @has_vendor_partition
<<EOS
  mobile.system.vendor.partition = "/dev/disk/by-partlabel/#{if @ab_update then "vendor_a" else "vendor" end}";
EOS
  else "" end
}

  boot.kernelParams = [
    # Extracted from an Android boot image
#{kernel_cmdline.map { |arg| "    \"#{arg}\"" }.join("\n")}
  ];

  mobile.system.type = "android";

#{
  if usb_mode
<<EOS
  mobile.usb.mode = "#{usb_mode}";
EOS
  else
<<EOS
  /* The usb mode could not be detected.
   * Assuming this is an older device, android_usb should be used.
   * For a newer device, gadgetfs is to be used.
   */
  mobile.usb.mode = null;
EOS
  end
}

  /* To be changed by the author, though those may or may work with any device. */
  # Google
  mobile.usb.idVendor = "18D1";
  # "Nexus 4"
  mobile.usb.idProduct = "D001";

#{
  if usb_mode == "gadgetfs"
    if rndis_gadget
<<EOS
  mobile.usb.gadgetfs.functions = {
    /* This rndis gadget has been auto-detected. */
    rndis = "#{rndis_gadget}";
  };
EOS
    else
<<EOS
  mobile.usb.gadgetfs.functions = {
    /* No known rndis gadget could be conclusively found.
     * The following is a common valid value for rndis. Uncomment it and try it out.
     */
    #rndis = "gsi.rndis";
  };
EOS
    end
  else "" end
  }
}
EOF
  .gsub(/ +\n/, "\n")
  .gsub(/\n\n+/, "\n\n")
    end
  end
end
